import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Slider from "@mui/material/Slider"
import { Group, Frame } from "./interfaces/basetype"
import {FrameListInfo} from '../components/FrameListInfo'

axios.defaults.baseURL = 'http://133.62.185.133:8000/api'

export default function Home() {

  const [frames, setFrames] = useState<Array<Frame>>([])
  
  const fetchFrames = async (frameNum:number) => {
    const frameData: Array<Frame> = await axios.get('/frame/' + frameNum.toString(), {
      params:{
        num:frameNum
      }
    })
    .then(res => res.data)
    setFrames(frameData)
  }
 
  console.log(frames)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <FrameListInfo frames={frames}></FrameListInfo>
        <Slider defaultValue={1} valueLabelDisplay='auto' 
                onChangeCommitted={(_, value) => {
                  const v = value as number
                  fetchFrames(v)
                  }} min={1} max={180000}/>
      </main>
    </div>
  )
}