import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Slider from "@mui/material/Slider"
import { Group, Frame } from "../interfaces/basetype"
import {FrameListInfo} from '../components/FrameListInfo'

export default function Home() {

  const [frames, setFrames] = useState<Array<Frame>>([])

  const fetchFrames = (frameNum:number) => {
    axios.get('/frames/' + frameNum.toString(), {
      params:{
        num:frameNum
      }
    })
    .then(res => setFrames(res.data))
  }

  useEffect(() => fetchFrames(1), [])
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FrameListInfo frames={frames}></FrameListInfo>
        <Slider defaultValue={1} valueLabelDisplay='auto' 
                onChangeCommitted={(_, value) => {
                  const v = value as number
                  fetchFrames(v)
                  }} min={1} max={180000}/>
      </main>
    </>
  )
}