import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Button from '@mui/material/Button'
import { useEffect, useState } from 'react'
import { PageNationTeacher } from '../interfaces/basetype'
import { TeachersTable } from '../components/TeachersTable'
import Pagenation from '@mui/material/Pagination'
import { resourceLimits } from 'worker_threads'
import Box from "@mui/material/Box"

const PAGE_CONTENT_NUM = 50

export default function Home() {

  const [teachersData, setTeachersData] = useState<PageNationTeacher>({
    count:0, next:null, previous:null, results:[]
  })

  const fetchTeachers = (page:number | null) => {
    let headers = {}
    if (page != null){
      headers = {
        params:{
            limit:PAGE_CONTENT_NUM, 
            offset:PAGE_CONTENT_NUM * (page - 1)
        }
      }
    }
    axios.get('/teacher/wd', headers).then(res => setTeachersData(res.data))
  }
  
  useEffect(() => fetchTeachers(null), [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Box sx={{minWidth:300, maxWidth:500}}>
            <TeachersTable teachers={teachersData?.results}></TeachersTable>
            <Pagenation
           count={Math.ceil(teachersData.count / PAGE_CONTENT_NUM)}
           onChange = {(e, page) => fetchTeachers(page)}
           />
          </Box>
      </main>
    </div>
  )
}